FROM mwanjemike767/cadise-api-base:1.0.0

WORKDIR /app

ENV MONGO_URI="Enter MONGO_URI here in quotes"
ENV PORT=PORT_NUMBER_HERE_WITHOUT_QUOTES

COPY requirements.txt requirements.txt
# installing dependencies for project
RUN pip3 install -r requirements.txt

COPY . .

CMD ["python3", "app.py"]
